Repository SE701-T5/Frontend, pull requests merged in 2022-03, with the labels that each got.

#8 setup react app
  .gitignore
  package-lock.json
  package.json
  public/_redirects
  public/index.html
  public/robots.txt
  src/App.css
  src/App.js
  src/api/index.js
  src/components/components.md
  src/hooks/hooks.md
  src/index.css
  src/index.js
  src/pages/Homepage/Homepage.jsx
  src/pages/Homepage/homepage.css
  src/pages/Homepage/index.js
  src/pages/pages.md
Labels: documentation, Setup

#16 set up material ui packages
  package-lock.json
  package.json
Labels: Setup

#19 Added MUI Icons Library.
  package-lock.json
  package.json
Labels: bug

#5 Update README.md
  README.md
Labels: documentation

#13 Add pull_request_template.md
  .github/pull_request_template.md
Labels: documentation

#10 Add CODE_OF_CONDUCT.md
  .github/CODE_OF_CONDUCT.md
Labels: documentation

#3 Add CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: documentation

#23 Post preview component
  package-lock.json
  package.json
  public/uoa.jpg
  src/App.js
  src/components/postPreviewComponent/PostPreviewComponent.jsx
  src/components/postPreviewComponent/index.js
  src/components/postPreviewComponent/postPreviewComponent.css
  src/index.css
  src/pages/Homepage/homepage.css
  src/pages/componentsTesting/ComponentsTesting.jsx
Labels: enhancement

#22 Create nav bar
  public/logo.svg
  src/App.js
  src/components/NavBar/NavBar-styles.js
  src/components/NavBar/NavBar.jsx
Labels: enhancement

#21 Issue #12 homepage layout
  src/App.css
  src/components/PopularCommunity/PopularCommunity.css
  src/components/PopularCommunity/PopularCommunity.jsx
  src/pages/Homepage/COMPSYS726.png
  src/pages/Homepage/Homepage.jsx
  src/pages/Homepage/SOFTENG701.png
  src/pages/Homepage/SOFTENG754.png
  src/pages/Homepage/homepage.css
Labels: enhancement

#28 Add post preview and fix multiple stylings in homepage
  public/logo.svg
  src/App.css
  src/components/NavBar/NavBar.jsx
  src/components/postPreviewComponent/PostPreviewComponent.jsx
  src/components/postPreviewComponent/postPreviewComponent.css
  src/pages/Homepage/Homepage.jsx
  src/pages/Homepage/homepage.css
Labels: bug, enhancement

#25 Login
  src/App.js
  src/context/AuthProvider.jsx
  src/index.css
  src/index.js
  src/pages/LoginRegister/ForgotPasswordPage.jsx
  src/pages/LoginRegister/LoginForm.jsx
  src/pages/LoginRegister/LoginPage.css
  src/pages/LoginRegister/LoginPage.jsx
  src/pages/LoginRegister/RegisterForm.jsx
  src/pages/LoginRegister/RegisterPage.jsx
Labels: enhancement

#30 New post page layout
  src/App.js
  src/pages/newPost/NewPost.jsx
  src/pages/newPost/newPost.css
Labels: enhancement

#36 Pull/issue35
  src/components/NavBar/NavBar.jsx
  src/pages/newPost/NewPost.jsx
  src/pages/newPost/newPost.css
Labels: enhancement

#41 Fix pull_request_template.md Broken Link
  .github/pull_request_template.md
  .gitignore
Labels: bug, documentation

#43 Add CODEOWNERS
  .github/CODEOWNERS
Labels: documentation

#46 Posts page basic layout
  src/App.js
  src/pages/Posts/Posts.jsx
  src/pages/Posts/posts.css
Labels: enhancement

#45 Connect header with user authorization context and fix header bug.
  src/assets/logo.svg
  src/components/NavBar/NavBar.jsx
  src/context/AuthProvider.jsx
Labels: bug

#49 Pull/issue47
  src/pages/Posts/Posts.jsx
Labels: enhancement

#39 add neW community page
  src/App.js
  src/pages/Communities/CommunitiesPage.jsx
  src/pages/newCommunity/NewCommunity.jsx
  src/pages/newCommunity/newCommunity.css
Labels: enhancement

#51 pull/issue50
  src/pages/LoginRegister/LoginForm.jsx
  src/pages/LoginRegister/LoginPage.css
  src/pages/LoginRegister/RegisterForm.jsx
Labels: bug, enhancement

#48 Added CommunityPreviewComponent and Communities page
  src/App.js
  src/components/communityPreviewComponent/CommunityPreviewComponent.jsx
  src/components/communityPreviewComponent/communityPreviewComponent.css
  src/pages/Communities/Communities.jsx
  src/pages/Communities/communities.css
Labels: enhancement

#38 Post page
  src/App.css
  src/App.js
  src/components/comment/Comment.jsx
  src/components/comment/comment.css
  src/pages/Post/Post.jsx
  src/pages/Post/Reply/Reply.jsx
  src/pages/Post/Reply/index.js
  src/pages/Post/Reply/reply.css
  src/pages/Post/index.js
  src/pages/Post/post.css
Labels: enhancement

#56 Added communities search function
  src/pages/Communities/Communities.jsx
Labels: enhancement

#52 Finished all requirements in #31
  .gitignore
  src/App.js
  src/index.css
  src/pages/Community/index.css
  src/pages/Community/index.js
Labels: enhancement

#54 make general fixes
  README.md
  src/api/index.js
  src/components/postPreviewComponent/PostPreviewComponent.jsx
  src/components/postPreviewComponent/postPreviewComponent.css
  src/pages/Communities/Communities.jsx
  src/pages/Communities/communities.css
  src/pages/Homepage/Homepage.jsx
  src/pages/Post/Post.jsx
  src/pages/Posts/Posts.jsx
Labels: bug, documentation, enhancement

#58 Fix nav bar style
  src/components/NavBar/NavBar.jsx
  src/pages/Homepage/homepage.css
Labels: enhancement

#90 Setup API Hook, add prettier, add basic JS type-checking with TS
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/pull_request_template.md
  .husky/.gitignore
  .husky/pre-commit
  .prettierrc.js
  README.md
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/api/index.js
  src/components/NavBar/NavBar.jsx
  src/components/PopularCommunity/PopularCommunity.css
  src/components/PopularCommunity/PopularCommunity.jsx
  src/components/comment/Comment.jsx
  src/components/comment/comment.css
  src/components/communityPreviewComponent/CommunityPreviewComponent.jsx
  src/components/communityPreviewComponent/communityPreviewComponent.css
  src/components/components.md
  src/context/AuthProvider.jsx
  src/hooks/hooks.md
  src/hooks/useApi.js
  src/index.css
  src/pages/Communities/Communities.jsx
  src/pages/Community/index.css
  src/pages/Community/index.js
  src/pages/Homepage/homepage.css
  src/pages/Post/Reply/Reply.jsx
  src/pages/Post/Reply/reply.css
  src/pages/Post/post.css
  src/pages/Posts/posts.css
  src/pages/componentsTesting/ComponentsTesting.jsx
  src/pages/pages.md
  tsconfig.json
Labels: Setup
